<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="FluentValidation" Version="11.*" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="11.*" />
    <PackageVersion Include="EFCore.NamingConventions" Version="9.0.*" />
    <PackageVersion Include="MediatR" Version="14.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.*" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.*" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageVersion Include="NetArchTest.Rules" Version="1.*" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.*" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.*" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageVersion Include="xunit" Version="2.9.*" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.*" />
  </ItemGroup>

</Project>
